### ISSUE TITLE
D3.11.4 - Report on the Preparation for Full-Scale DAC Matches

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match#22]
- Change request [C037](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C037_WP3.11_WA_award_rebaseline.pdf?api=v2) approved at 01/MAR/22 Exec resulted in due date changed from PM32 (28/FEB/22) to PM42 (14/DEC/22)
- [Change Request C022]( https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C022-Rebaselining_WP3.11.pdf?api=v2) resulted in deliverable title changing and due date moving from 30/NOV/21 (PM29) to 28/FEB/22 (PM32).

**Comment by tms-epcc** [comment]
- change request submitted to move due date to 31/JAN/23

**Comment by tms-epcc** [comment]
02/FEB/23
- change request [C056](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C056-WP3.11-Remove-MS027-Update-D3.11.4-Deadline.pdf?api=v2) moved the due date from 14/DEC/22 (PM42) to 31/JAN/23 (PM43)

**Comment by tms-epcc** [comment]
27/APR/23
- deliverable published via [LSST:UK public page](https://lsst-uk.atlassian.net/wiki/download/attachments/1146928/LUSC-B-37-D3.11.4_Full_Scale_DAC_Matches_report.pdf?api=v2) following Exec Group approval
