### ISSUE TITLE
S3: DP0.2/HSC

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match#46]
An LSST-like cross-match, we plan to match DP0.2/HSC against some other catalogue (such as Gaia), to verify the matching process on the most up-to-date LSST data formats as possible.

**Comment by tms-epcc** [comment]
05/APR/23
- this may happen at some point in the future hence is not removed

**Comment by Onoddil** [comment]
Performed Gaia-HSC match, confirming data products expected from LSST.
