### ISSUE TITLE
T3.3.1.2: Super-Match Code Framework

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match#66]
Once #65 is complete -- or in parallel, if the project is broken down into multiple serial sections -- then the framework can be constructed. This will either take the form of separate Python-based code that runs in post-processing once all LSST matches are performed, or e.g. SQL queries that can be performed on-the-fly, size and scale of project depending.

**Comment by tms-epcc** [comment]
03/AUG/23
- this is "Establish how to the apply the algorithm we have developed within the data structures we have
created. " from the Jun'23 QU

**Comment by tms-epcc** [comment]
12/SEP/23
- little progress due to early Science verification.  
- @Onoddil will speak with @MikeeRead abut starting this
