### ISSUE TITLE
S5: Run DAC cross-matches

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match#9]
Essentially a placeholder goal currently, the final step of WP3.11, once catalogues are ingested into the DAC and the cross-match code has been written, tested, and implemented on the DAC as well, is to run any and all cross-matches for deployment on the DAC as an online service.

**Comment by tms-epcc** [comment]
05/APR/23
- ticket closed since this will occur as necessary on an ad-hoc basis
